

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

aws:
  s3:
    accessKey: ${AWS_S3_ACCESSKEY}
    secretKey: ${AWS_S3_SECRETKEY}

jwt:
  secretKey: 51655468576D5A7134743677397A24432646294A404E635266556A586E327235
  accessTokenCookieName: mh-jwt-access
  accessTokenExpirationMs: 300000
  refreshTokenCookieName: mh-jwt-refresh
  refreshTokenExpirationMs: 1800000

server:
  servlet:
    context-path: /api